REPLACE INTO ?:affiliate_plans (plan_id, payout_types, commissions, min_payment, product_ids, category_ids, promotion_ids, cookie_expiration, method_based_selling_price, use_coupon_commission, status) VALUES (11, 'a:6:{s:12:"init_balance";a:2:{s:5:"value";d:1;s:10:"value_type";s:1:"A";}s:4:"show";a:2:{s:5:"value";d:0.01000000000000000020816681711721685132943093776702880859375;s:10:"value_type";s:1:"A";}s:5:"click";a:2:{s:5:"value";d:1;s:10:"value_type";s:1:"A";}s:4:"sale";a:2:{s:5:"value";d:0;s:10:"value_type";s:1:"P";}s:12:"new_customer";a:2:{s:5:"value";d:2;s:10:"value_type";s:1:"A";}s:11:"new_partner";a:2:{s:5:"value";d:3;s:10:"value_type";s:1:"A";}}', '5;2.5;1', '10.00', 'a:3:{i:197;a:2:{s:5:"value";d:5;s:10:"value_type";s:1:"A";}i:97;a:2:{s:5:"value";d:10;s:10:"value_type";s:1:"P";}i:67;a:2:{s:5:"value";d:15;s:10:"value_type";s:1:"P";}}', 'a:3:{i:224;a:2:{s:5:"value";d:10;s:10:"value_type";s:1:"P";}i:225;a:2:{s:5:"value";d:10;s:10:"value_type";s:1:"P";}i:226;a:2:{s:5:"value";d:10;s:10:"value_type";s:1:"P";}}', 'a:2:{i:109;a:2:{s:5:"value";d:10;s:10:"value_type";s:1:"A";}i:105;a:2:{s:5:"value";d:2;s:10:"value_type";s:1:"P";}}', 15, 'N', 'N', 'A');

/*
type: T - text, G - Graphic, P - product, C - category
*/
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('28', '120', '48', 'T', 'C', '93', 'N', 'B', 'N', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('24', '150', '70', 'T', 'C', '152,92,141,155', 'Y', 'B', 'N', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('18', '120', '50', 'T', 'C', '115', 'N', 'B', 'Y', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('32', '190', '50', 'T', 'P', '', 'N', 'B', 'N', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('35', '200', '200', 'T', 'P', '890,867', 'Y', 'B', 'N', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('36', '120', '30', 'T', 'U', 'http://demo.cs-cart.com/professional/index.php?dispatch=pages.view&page_id=3', 'N', 'B', 'N', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('38', '100', '40', 'T', 'G', '3', 'N', 'B', 'N', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('42', '250', '150', 'P', 'U', 'a:5:{s:5:\"image\";s:1:\"B\";s:12:\"product_name\";s:1:\"T\";s:17:\"short_description\";s:1:\"T\";s:5:\"align\";s:6:\"center\";s:6:\"border\";s:1:\"Y\";}', 'N', 'B', 'Y', 'Y', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('57', '0', '0', 'G', 'G', '1', 'Y', 'B', 'Y', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('55', '0', '0', 'G', 'C', '85,122,111,119', 'Y', 'B', 'N', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('56', '0', '0', 'G', 'P', '1529', 'Y', 'B', 'Y', 'N', 'N', 'A');
REPLACE INTO ?:aff_banners (banner_id, width, height, type, link_to, data, show_title, text_location, new_window, to_cart, show_url, status) VALUES ('61', '0', '0', 'T', 'G', '2', 'Y', 'B', 'Y', 'N', 'N', 'A');

REPLACE INTO ?:aff_groups (group_id, link_to, data, status) VALUES ('1', 'C', '208,224,225', 'A');
REPLACE INTO ?:aff_groups (group_id, link_to, data, status) VALUES ('2', 'P', '230,158,60,186,152', 'A');
REPLACE INTO ?:aff_groups (group_id, link_to, data, status) VALUES ('3', 'U', 'http://url_group.com.nn', 'A');
